apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsbackend
  labels:
    app: wsbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wsbackend
  template:
    metadata:
      labels:
        app: wsbackend
    spec:
      containers:
        - name: wsbackend
          image: kush233/draw-websocket:6fd704bf0a07da7380e43e1776d2e9639438fe61
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
