apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wsbackend
  namespace: doodlemesh
spec:
  hosts:
    - draw.kushan23.com
  gateways:
    - istio-system/platform-gateway
  http:
    - match:
        - uri:
            prefix: /ws
      route:
        - destination:
            host: wsbackend
            port:
              number: 80
