apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wsbackend
  namespace: doodlemesh
spec:
  hosts:
    - draw.kushan23.com
  gateways:
    - istio-system/platform-gateway
  http:
    - match:
        - uri:
            prefix: /ws
      route:
        - destination:
            host: wsbackend.doodlemesh.svc.cluster.local
            port:
              number: 80
      timeout: 0s
      headers:
        request:
          set:
            Connection: "upgrade"
            Upgrade: "websocket"
